version: '3'
services:
  frontend:
    restart: always
    container_name: "frontend"
    build:
      context: .
      dockerfile: Dockerfile-test
    ports:
      - "3000:3000"
    volumes:
      - ./dist/HTML:/usr/share/nginx/html

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    depends_on:
      - "nginx-proxy"
      - "nginx"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy

  nginx:
    container_name: "nginx-container"
    build:
      context: .
      dockerfile: DockerfileNginx-test
    volumes:
      - dhparam:/etc/nginx/dhparam
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:ro

    restart: always

    environment:
      - VIRTUAL_HOST=li1871-48.members.linode.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=li1871-48.members.linode.com
      - LETSENCRYPT_EMAIL=max@conquers.co
    depends_on:
      - "frontend"


volumes:
  certs:
  html:
  vhost:
  dhparam: